USERS_REST_SERVER_MAINCLASS=sd2526.trab.impl.rest.servers.RestUsersServer
USERS_REST_PORT=3456
USERS_REST_EXTRA_ARGS=-secret secret

USERS_GRPC_SERVER_MAINCLASS=
USERS_GRPC_PORT=
USERS_GRPC_EXTRA_ARGS=


MESSAGES_REST_SERVER_MAINCLASS=sd2526.trab.impl.rest.servers.RestMessagesServer
MESSAGES_REST_PORT=4567
MESSAGES_REST_EXTRA_ARGS=-secret secret

MESSAGES_GRPC_SERVER_MAINCLASS=
MESSAGES_GRPC_PORT=
MESSAGES_GRPC_EXTRA_ARGS=


GATEWAY_REST_SERVER_MAINCLASS=sd2526.trab.impl.rest.servers.RestGatewayServer
GATEWAY_REST_PORT=6666
GATEWAY_REST_EXTRA_ARGS=-secret secret


DISCOVERY_MULTICAST_IP=226.226.226.226
DISCOVERY_MULTICAST_PORT=2266

MESSAGES_REST_PROXY_SERVER_MAINCLASS=
MESSAGES_REST_PROXY_PORT=
MESSAGES_REST_PROXY_EXTRA_ARGS=

MESSAGES_REP_SERVER_MAINCLASS=
MESSAGES_REP_PORT=
MESSAGES_REP_EXTRA_ARGS_FIRST=
MESSAGES_REP_EXTRA_ARGS_OTHER=

USERS_KEYSTORES=users.ourorg0,users-0.ks,changeit users.ourorg1,users-1.ks,changeit users.ourorg2,users-2.ks,changeit
SERVERS_KEYSTORES=messages0.ourorg0,messages0-0.ks,changeit messages1.ourorg0,messages1-0.ks,changeit messages2.ourorg0,messages2-0.ks,changeit messages0.ourorg1,messages0-1.ks,changeit messages1.ourorg1,messages1-1.ks,changeit messages2.ourorg1,messages2-1.ks,changeit messages.ourorg2,messages-2.ks,changeit
CLIENT_TRUSTSTORE=client-truststore.ks
CLIENT_TRUSTSTORE_PWD=changeit